#!/bin/bash -l
set -euo pipefail

# Put our custom Jupyter Server config into appropriate platform
# This path is determined by looking at output of `jupyter --path` in the hub
# We copy both to notebook server config and jupyter server config, because either can be
# used in the JupyterHub.
cp custom_jupyter_server_config.json ${NB_PYTHON_PREFIX}/etc/jupyter/jupyter_server_config.d/
cp custom_jupyter_server_config.json ${NB_PYTHON_PREFIX}/etc/jupyter/jupyter_notebook_config.d/

# Associate .qgs files with QGIS desktop application
MIME_PACKAGE_DIR=~/.local/share/mime/packages
mkdir -p ${MIME_PACKAGE_DIR}
wget https://raw.githubusercontent.com/qgis/QGIS/ltr-3_28/debian/qgis.xml -O ${MIME_PACKAGE_DIR}/qgis.xml
