name: Build container image

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
    secrets:
      username:
        required: false
      password:
        required: false

jobs:
  build:
    env:
      PACKAGE: cryo-hub-image
      REGISTRY: quay.io
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - name: Checkout files in repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Image metadata
        id: image
        uses: docker/metadata-action@v6
        env:
            DOCKER_METADATA_SHORT_SHA_LENGTH: 12
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.PACKAGE }}
          tags: |
            type=sha,prefix=

      - name: Cache metadata
        id: cache
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE }}-cache
          tags: |
            type=raw,value=latest

      - name: Authenticate with distribution registry
        if: github.repository == 'CryoInTheCloud/hub-image' && github.event_name == 'push'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Authenticate with cache registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v4

      - name: Install repo2docker
        run: pip install git+https://github.com/jupyterhub/repo2docker.git@6b59fafc364a549d1709866b0c559d097a052010

      - name: Run repo2docker
        env:
          PUSH_QUESTION: ${{ github.event_name == 'push' && '--push' || '--no-push' }}
          STEPS_CACHE_OUTPUTS_TAGS: ${{ steps.cache.outputs.tags }}
          STEPS_IMAGE_OUTPUTS_TAGS: ${{ steps.image.outputs.tags }}
        run: >
          jupyter-repo2docker
          $PUSH_QUESTION
          --no-run
          --user-id 1000
          --user-name jovyan
          --target-repo-dir /srv/repo
          --appendix "$(< appendix)"
          --image-name ${STEPS_IMAGE_OUTPUTS_TAGS}
          --DockerEngine.extra_buildx_build_args=--cache-from="type=registry,ref=${STEPS_CACHE_OUTPUTS_TAGS}"
          --DockerEngine.extra_buildx_build_args=--cache-to="type=registry,ref=${STEPS_CACHE_OUTPUTS_TAGS},mode=max"
          .
