# Runs conda-lock against environment.yml for reproducible environments
name: Conda Lock

on:
  repository_dispatch:
    types:
      - condalock-command

permissions: {}

jobs:
  condalock:
    permissions:
      contents: write  # for git push
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      # Generate token from CryoInTheCloud bot
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Checkout the pull request branch
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          persist-credentials: true

      # Install conda-lock library with Micromamba
      - name: Install conda-lock with Micromamba
        uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
        with:
          environment-name: conda-lock-env
          create-args: conda-lock
          init-shell: none
          cache-downloads-key: micromamba-downloads

      # Generate unified 'conda-lock.yml' and platform-specific lockfiles
      - name: Run conda-lock
        shell: micromamba-shell {0}
        run: >
          conda-lock lock
          --kind lock
          --kind explicit
          --file environment.yml
          --without-cuda
          --platform linux-64

      # Commit the change to the PR branch if any changes
      - name: Commit condalock files to PR
        run: |
          if [[ $(git ls-files --modified) ]]; then
            git config --global user.name 'actions-bot'
            git config --global user.email '58130806+actions-bot@users.noreply.github.com'
            git commit --all --message "[condalock-command] autogenerated conda-lock files"
            git push
          fi

      # Add an emoji reaction to comment to indicate the script completed successfully
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
