name: Slash Command Dispatch

on:
  issue_comment:
    types:
      - created
      # - edited  # add for test purposes, otherwise avoid to prevent processing unnecessary events

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  slashCommandDispatch:
    permissions:
      pull-requests: write  # for peter-evans/slash-command-dispatch to create PR reaction
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      # Generate token from CryoInTheCloud bot
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            condalock
          issue-type: pull-request
          permission: none
