name: Test building container image

on:
  pull_request:
    paths:
      - ".binder/apt.txt"
      - ".binder/environment.yml"
      - ".binder/postBuild"
      - ".binder/start"
      - "mime"
      - "appendix"
      - "conda-linux-64.lock"
      - "conda-lock.yml"
      - "custom_jupyter_server_config.json"
      - "qgis.desktop"
      - ".github/workflows/build.yaml"  # rebuild if the build workflow changes
      - ".github/workflows/test.yaml"  # rebuild if this workflow changes

permissions: {}  # prevent excessive permissions on workflow level

jobs:
  call:
    uses: ./.github/workflows/build.yaml
    permissions:
      packages: write  # needed to upload and publish cache to GitHub Packages
